version: '3'
services:
  apiweb1:
          image: myhttpd:v2
          build: .
          ports:
             - "81:80"
  apiweb2:
          image: myhttpd:v2
          build: .
          ports:
             - "82:80"
  load-balancer:
          image: nginx:latest
          ports:
             - "80:80"
